---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.toml: |
    [Global]
      checkNewVersion = false
      sendAnonymousUsage = false
    [log]
      level = "WARN"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entryPoint]
          to = "https"
          scheme = "https"
          permanent = true
          priority = 42
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.http.tls]
    [providers]
      [providers.kubernetesCRD]
      # Enable kubernetes ingress provider to expose cert-manager challenge
      [providers.kubernetesIngress]
        ingressClass = "traefik-cert-manager"
    [api]
      dashboard = true
      insecure = true
    [ping]
    [metrics]
      [metrics.prometheus]
      buckets = [0.1,0.3,1.2,5.0]
